import Foundation

enum ScheduleCLine: String, CaseIterable, Codable, Identifiable {
    var id: String { rawValue }
    case line18Software = "Line 18 · Office & Software SaaS"
    case line22Supplies = "Line 22 · Supplies & Hardware"
    case line24bMeals = "Line 24b · Deductible Business Meals (50%)"
    case line27aOther = "Line 27a · Other Business Expenses"

    var irsCode: String {
        switch self {
        case .line18Software: return "Line 18"
        case .line22Supplies: return "Line 22"
        case .line24bMeals: return "Line 24b"
        case .line27aOther: return "Line 27a"
        }
    }
}

struct ScheduleCLineItem: Identifiable, Codable {
    var id: UUID
    let date: Date
    let merchant: String
    let irsLine: ScheduleCLine
    let grossAmount: Decimal
    let deductibleAmount: Decimal
    let cardLast4: String?
    let cardNickname: String
    let category: ReceiptCategory
    let notes: String?
}

struct ScheduleCTaxReport: Codable {
    let year: Int
    let grossBusinessSpend: Decimal
    let totalDeductibleAmount: Decimal
    let byLine: [ScheduleCLine: Decimal]
    let lineItems: [ScheduleCLineItem]

    static let empty = ScheduleCTaxReport(year: 2026, grossBusinessSpend: 0, totalDeductibleAmount: 0, byLine: [:], lineItems: [])
}

enum ScheduleCTaxEngine {

    /// Classifies receipts into IRS Schedule-C line items.
    static func generateReport(year: Int = 2026, receipts: [ReceiptPayload]) -> ScheduleCTaxReport {
        var items: [ScheduleCLineItem] = []
        var grossTotal: Decimal = 0
        var deductibleTotal: Decimal = 0
        var lineTotals: [ScheduleCLine: Decimal] = [:]

        let cal = Calendar.current
        for r in receipts {
            let receiptYear = cal.component(.year, from: r.transactionDate)
            if receiptYear != year { continue }

            // Classify IRS line
            var line: ScheduleCLine? = nil
            var multiplier: Decimal = 1.0

            switch r.category {
            case .software, .subscriptions:
                line = .line18Software
            case .shopping:
                line = .line22Supplies
            case .dining:
                line = .line24bMeals
                multiplier = Decimal(string: "0.50")! // 50% IRS limit
            case .business, .travel, .transport, .education, .utilities:
                line = .line27aOther
            case .groceries, .health, .other, .unknown:
                if r.notes?.lowercased().contains("tax") == true || r.notes?.lowercased().contains("business") == true {
                    line = .line27aOther
                }
            }

            guard let irsLine = line else { continue }

            let cardName = CardPortfolio.displayName(for: r.cardLast4)
            let deductible = r.amount * multiplier

            let item = ScheduleCLineItem(
                id: r.id,
                date: r.transactionDate,
                merchant: r.merchant,
                irsLine: irsLine,
                grossAmount: r.amount,
                deductibleAmount: deductible,
                cardLast4: r.cardLast4,
                cardNickname: cardName,
                category: r.category,
                notes: r.notes
            )
            items.append(item)
            grossTotal += r.amount
            deductibleTotal += deductible
            lineTotals[irsLine, default: 0] += deductible
        }

        items.sort { $0.date > $1.date }

        return ScheduleCTaxReport(
            year: year,
            grossBusinessSpend: grossTotal,
            totalDeductibleAmount: deductibleTotal,
            byLine: lineTotals,
            lineItems: items
        )
    }

    /// Generates IRS Schedule-C CSV for accountant import.
    static func exportCSV(report: ScheduleCTaxReport) -> String {
        var lines: [String] = []
        lines.append("IRS Line,Date,Merchant,Category,Gross Amount,Deductible Amount,Payment Method,Notes")

        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"

        for item in report.lineItems {
            let dateStr = f.string(from: item.date)
            let noteClean = (item.notes ?? "").replacingOccurrences(of: "\"", with: "\"\"")
            let row = "\"\(item.irsLine.irsCode)\",\"\(dateStr)\",\"\(item.merchant)\",\"\(item.category.label)\",\(item.grossAmount),\(item.deductibleAmount),\"\(item.cardNickname)\",\"\(noteClean)\""
            lines.append(row)
        }

        return lines.joined(separator: "\n")
    }

    /// Formats a complete markdown tax report for CPA review.
    static func exportCPAMarkdown(report: ScheduleCTaxReport) -> String {
        var md = "# IRS Schedule-C Tax Deduction Packet (\(report.year))\n"
        md += "Generated by macsync Private Intelligence on \(Date())\n\n"
        md += "### Summary of Deductions\n"
        md += "- **Gross Business Expense**: \(SpendFormat.amount(report.grossBusinessSpend))\n"
        md += "- **Total Deductible (Net)**: **\(SpendFormat.amount(report.totalDeductibleAmount))**\n\n"
        md += "| IRS Line Number | Category Description | Deductible Total |\n"
        md += "| :--- | :--- | :--- |\n"
        for line in ScheduleCLine.allCases {
            let amt = report.byLine[line] ?? 0
            md += "| **\(line.irsCode)** | \(line.rawValue) | **\(SpendFormat.amount(amt))** |\n"
        }
        md += "\n### Itemized Deductible Receipts\n\n"
        md += "| Date | Merchant | IRS Line | Gross | Deductible | Card |\n"
        md += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
        let f = DateFormatter(); f.dateFormat = "MM/dd/yyyy"
        for item in report.lineItems {
            md += "| \(f.string(from: item.date)) | \(item.merchant) | \(item.irsLine.irsCode) | \(SpendFormat.amount(item.grossAmount)) | \(SpendFormat.amount(item.deductibleAmount)) | \(item.cardNickname) |\n"
        }
        return md
    }
}
